name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release

    - name: Publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET-API-KEY }}
      run: dotnet nuget push bin/Release/*.nupkg --api-key $NUGET-API-KEY --source https://api.nuget.org/v3/index.json
